version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
      JWT_SECRET: YOUR_JWT_KEY
      DB_NAME: pager
      DB_USERNAME: pager_user
      DB_HOSTNAME: postgres
    ports:
      - "3000:3000"
    command: npm run migrate:dev
    command: npm run start

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: pager_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pager